n_tether: 8

tether_configuration:
    '0':
        attach_pos: {x: 0.4, y: -0.4, z: 0.15}
        anchor_pos: {x: 5.0, y: 5.0, z: 0.0}
        max_tension: 5.0
    '1':
        attach_pos: {x: 0.4, y: -0.4, z: -0.15}
        anchor_pos: {x: -5.0, y: -5.0, z: 0.0}
        max_tension: 5.0
    '2':
        attach_pos: {x: 0.4, y: 0.4, z: 0.15}
        anchor_pos: {x: -5.0, y: 5.0, z: 0.0}
        max_tension: 5.0
    '3':
        attach_pos: {x: 0.4, y: 0.4, z: -0.15}
        anchor_pos: {x: 5.0, y: -5.0, z: 0.0}
        max_tension: 5.0
    '4':
        attach_pos: {x: -0.4, y: -0.4, z: 0.15}
        anchor_pos: {x: 5.0, y: -5.0, z: 0.0}
        max_tension: 5.0
    '5':
        attach_pos: {x: -0.4, y: -0.4, z: -0.15}
        anchor_pos: {x: -5.0, y: 5.0, z: 0.0}
        max_tension: 5.0
    '6':
        attach_pos: {x: -0.4, y: 0.4, z: 0.15}
        anchor_pos: {x: -5.0, y: -5.0, z: 0.0}
        max_tension: 5.0
    '7':
        attach_pos: {x: -0.4, y: 0.4, z: -0.15}
        anchor_pos: {x: 5.0, y: 5.0, z: 0.0}
        max_tension: 5.0
